import type { DailyQuestion } from '@/types/daily-questions'

/**
 * Pool of 60+ questions across 7 categories for daily user context gathering
 */
export const QUESTION_POOL: readonly DailyQuestion[] = [
  // ==================== PERSONAL (10 questions) ====================
  {
    id: 'personal-1',
    category: 'personal',
    question: 'Hast du Haustiere?',
    inputType: 'select',
    options: ['Ja, Hund(e)', 'Ja, Katze(n)', 'Ja, andere', 'Nein', 'Mehrere verschiedene'],
    aiContextKey: 'haustiere',
    priority: 5,
  },
  {
    id: 'personal-2',
    category: 'personal',
    question: 'Wo lebst du aktuell?',
    inputType: 'text',
    placeholder: 'z.B. Berlin, München, Wien...',
    aiContextKey: 'wohnort',
    priority: 3,
  },
  {
    id: 'personal-3',
    category: 'personal',
    question: 'Wie ist dein Familienstand?',
    inputType: 'select',
    options: ['Single', 'In einer Beziehung', 'Verheiratet', 'Verwitwet', 'Lieber nicht sagen'],
    aiContextKey: 'familienstand',
    priority: 6,
  },
  {
    id: 'personal-4',
    category: 'personal',
    question: 'Hast du Kinder?',
    inputType: 'select',
    options: ['Ja', 'Nein', 'Plane es', 'Lieber nicht sagen'],
    aiContextKey: 'kinder',
    priority: 6,
  },
  {
    id: 'personal-5',
    category: 'personal',
    question: 'Was ist deine Muttersprache?',
    inputType: 'text',
    placeholder: 'z.B. Deutsch, Englisch...',
    aiContextKey: 'muttersprache',
    priority: 4,
  },
  {
    id: 'personal-6',
    category: 'personal',
    question: 'Welche Sprachen sprichst du noch?',
    inputType: 'text',
    placeholder: 'z.B. Englisch, Französisch...',
    aiContextKey: 'weitere_sprachen',
    priority: 5,
  },
  {
    id: 'personal-7',
    category: 'personal',
    question: 'Was ist dein Lieblingsgericht?',
    inputType: 'text',
    placeholder: 'z.B. Pasta, Sushi, Currywurst...',
    aiContextKey: 'lieblingsgericht',
    priority: 8,
  },
  {
    id: 'personal-8',
    category: 'personal',
    question: 'Wie alt bist du ungefähr?',
    inputType: 'select',
    options: ['Unter 25', '25-34', '35-44', '45-54', '55+', 'Lieber nicht sagen'],
    aiContextKey: 'altersgruppe',
    priority: 4,
  },
  {
    id: 'personal-9',
    category: 'personal',
    question: 'Was trinkst du am liebsten zum Arbeiten?',
    inputType: 'select',
    options: ['Kaffee', 'Tee', 'Wasser', 'Energy Drinks', 'Nichts bestimmtes'],
    aiContextKey: 'arbeitsgetraenk',
    priority: 9,
  },
  {
    id: 'personal-10',
    category: 'personal',
    question: 'Wie wichtig ist dir Work-Life-Balance?',
    inputType: 'select',
    options: ['Sehr wichtig', 'Wichtig', 'Neutral', 'Weniger wichtig', 'Arbeit hat Priorität'],
    aiContextKey: 'work_life_balance',
    priority: 3,
  },

  // ==================== CAREER (10 questions) ====================
  {
    id: 'career-1',
    category: 'career',
    question: 'Was motiviert dich bei der Arbeit am meisten?',
    inputType: 'select',
    options: ['Herausforderungen', 'Teamarbeit', 'Kreativität', 'Anerkennung', 'Einkommen', 'Impact'],
    aiContextKey: 'arbeitsmotivation',
    priority: 2,
  },
  {
    id: 'career-2',
    category: 'career',
    question: 'Arbeitest du lieber im Team oder alleine?',
    inputType: 'select',
    options: ['Definitiv im Team', 'Eher im Team', 'Beides gleich', 'Eher alleine', 'Definitiv alleine'],
    aiContextKey: 'teamarbeit_praeferenz',
    priority: 2,
  },
  {
    id: 'career-3',
    category: 'career',
    question: 'Wie lange bist du schon in deinem aktuellen Job?',
    inputType: 'select',
    options: ['Unter 1 Jahr', '1-2 Jahre', '3-5 Jahre', '5-10 Jahre', 'Über 10 Jahre'],
    aiContextKey: 'job_dauer',
    priority: 5,
  },
  {
    id: 'career-4',
    category: 'career',
    question: 'Hast du Führungsverantwortung?',
    inputType: 'select',
    options: ['Ja, großes Team', 'Ja, kleines Team', 'Teilweise', 'Nein', 'Ich bin selbstständig'],
    aiContextKey: 'fuehrungsverantwortung',
    priority: 3,
  },
  {
    id: 'career-5',
    category: 'career',
    question: 'Wie oft arbeitest du remote?',
    inputType: 'select',
    options: ['Vollständig remote', 'Meist remote', 'Hybrid', 'Meist im Büro', 'Vollständig im Büro'],
    aiContextKey: 'remote_arbeit',
    priority: 4,
  },
  {
    id: 'career-6',
    category: 'career',
    question: 'Wie viele Meetings hast du durchschnittlich pro Tag?',
    inputType: 'select',
    options: ['Keine', '1-2', '3-4', '5-6', 'Mehr als 6'],
    aiContextKey: 'meeting_frequenz',
    priority: 4,
  },
  {
    id: 'career-7',
    category: 'career',
    question: 'Mit welchen Abteilungen arbeitest du am meisten zusammen?',
    inputType: 'text',
    placeholder: 'z.B. Marketing, Sales, Engineering...',
    aiContextKey: 'zusammenarbeit_abteilungen',
    priority: 5,
  },
  {
    id: 'career-8',
    category: 'career',
    question: 'Was ist deine größte berufliche Stärke?',
    inputType: 'text',
    placeholder: 'z.B. Problemlösung, Kommunikation...',
    aiContextKey: 'berufliche_staerke',
    priority: 3,
  },
  {
    id: 'career-9',
    category: 'career',
    question: 'Wie gehst du mit Stress bei der Arbeit um?',
    inputType: 'select',
    options: ['Sport/Bewegung', 'Pausen machen', 'Priorisieren', 'Mit anderen reden', 'Durcharbeiten'],
    aiContextKey: 'stressbewaeltigung',
    priority: 4,
  },
  {
    id: 'career-10',
    category: 'career',
    question: 'Planst du in den nächsten Jahren einen Jobwechsel?',
    inputType: 'select',
    options: ['Ja, aktiv suchend', 'Vielleicht', 'Eher nicht', 'Definitiv nicht', 'Unsicher'],
    aiContextKey: 'jobwechsel_planung',
    priority: 7,
  },

  // ==================== GOALS (9 questions) ====================
  {
    id: 'goals-1',
    category: 'goals',
    question: 'Was ist dein wichtigstes Ziel für dieses Jahr?',
    inputType: 'text',
    placeholder: 'z.B. Beförderung, Projekt abschließen...',
    aiContextKey: 'jahresziel',
    priority: 1,
  },
  {
    id: 'goals-2',
    category: 'goals',
    question: 'Wo siehst du dich beruflich in 5 Jahren?',
    inputType: 'text',
    placeholder: 'z.B. Führungsposition, eigenes Unternehmen...',
    aiContextKey: 'fuenf_jahres_vision',
    priority: 2,
  },
  {
    id: 'goals-3',
    category: 'goals',
    question: 'Welche Fähigkeit möchtest du als nächstes lernen?',
    inputType: 'text',
    placeholder: 'z.B. Programmieren, Führung, Sprache...',
    aiContextKey: 'naechste_faehigkeit',
    priority: 3,
  },
  {
    id: 'goals-4',
    category: 'goals',
    question: 'Was ist dein größter Traum?',
    inputType: 'text',
    placeholder: 'z.B. Weltreise, Buch schreiben...',
    aiContextKey: 'groesster_traum',
    priority: 4,
  },
  {
    id: 'goals-5',
    category: 'goals',
    question: 'Wie wichtig ist dir beruflicher Aufstieg?',
    inputType: 'select',
    options: ['Sehr wichtig', 'Wichtig', 'Neutral', 'Weniger wichtig', 'Nicht wichtig'],
    aiContextKey: 'karriere_wichtigkeit',
    priority: 3,
  },
  {
    id: 'goals-6',
    category: 'goals',
    question: 'Hast du finanzielle Ziele für dieses Jahr?',
    inputType: 'select',
    options: ['Ja, sparen', 'Ja, investieren', 'Ja, Schulden tilgen', 'Keine speziellen', 'Lieber nicht sagen'],
    aiContextKey: 'finanzielle_ziele',
    priority: 6,
  },
  {
    id: 'goals-7',
    category: 'goals',
    question: 'Welches persönliche Projekt möchtest du starten?',
    inputType: 'text',
    placeholder: 'z.B. Blog, Podcast, App...',
    aiContextKey: 'persoenliches_projekt',
    priority: 5,
  },
  {
    id: 'goals-8',
    category: 'goals',
    question: 'Was möchtest du weniger machen?',
    inputType: 'text',
    placeholder: 'z.B. Social Media, Überstunden...',
    aiContextKey: 'weniger_machen',
    priority: 5,
  },
  {
    id: 'goals-9',
    category: 'goals',
    question: 'Was möchtest du mehr machen?',
    inputType: 'text',
    placeholder: 'z.B. Sport, Zeit mit Familie...',
    aiContextKey: 'mehr_machen',
    priority: 5,
  },

  // ==================== PREFERENCES (9 questions) ====================
  {
    id: 'preferences-1',
    category: 'preferences',
    question: 'Bist du eher ein Morgen- oder Abendmensch?',
    inputType: 'select',
    options: ['Definitiv Morgenmensch', 'Eher Morgenmensch', 'Weder noch', 'Eher Abendmensch', 'Definitiv Abendmensch'],
    aiContextKey: 'tageszeit_typ',
    priority: 2,
  },
  {
    id: 'preferences-2',
    category: 'preferences',
    question: 'Bevorzugst du Stadt oder Land?',
    inputType: 'select',
    options: ['Großstadt', 'Stadt', 'Vorort', 'Land', 'Egal'],
    aiContextKey: 'stadt_land_praeferenz',
    priority: 7,
  },
  {
    id: 'preferences-3',
    category: 'preferences',
    question: 'Wie informierst du dich über Neuigkeiten?',
    inputType: 'select',
    options: ['Social Media', 'Nachrichten-Apps', 'Podcasts', 'Zeitungen', 'Newsletter', 'Gespräche'],
    aiContextKey: 'nachrichten_quelle',
    priority: 6,
  },
  {
    id: 'preferences-4',
    category: 'preferences',
    question: 'Welchen Musik-Genre hörst du am liebsten?',
    inputType: 'text',
    placeholder: 'z.B. Pop, Rock, Klassik, Hip-Hop...',
    aiContextKey: 'musik_genre',
    priority: 8,
  },
  {
    id: 'preferences-5',
    category: 'preferences',
    question: 'Wie planst du am liebsten deinen Urlaub?',
    inputType: 'select',
    options: ['Alles durchgeplant', 'Grob geplant', 'Spontan', 'Mischung', 'Reise nicht gern'],
    aiContextKey: 'urlaubsplanung',
    priority: 7,
  },
  {
    id: 'preferences-6',
    category: 'preferences',
    question: 'Wie wichtig sind dir Routinen?',
    inputType: 'select',
    options: ['Sehr wichtig', 'Wichtig', 'Neutral', 'Weniger wichtig', 'Mag keine Routinen'],
    aiContextKey: 'routinen_wichtigkeit',
    priority: 4,
  },
  {
    id: 'preferences-7',
    category: 'preferences',
    question: 'Triffst du Entscheidungen eher schnell oder überlegt?',
    inputType: 'select',
    options: ['Sehr schnell', 'Eher schnell', 'Kommt drauf an', 'Eher überlegt', 'Sehr überlegt'],
    aiContextKey: 'entscheidungsstil',
    priority: 3,
  },
  {
    id: 'preferences-8',
    category: 'preferences',
    question: 'Wie gehst du mit Veränderungen um?',
    inputType: 'select',
    options: ['Liebe sie', 'Mag sie', 'Neutral', 'Brauche Zeit', 'Mag sie nicht'],
    aiContextKey: 'veraenderungstoleranz',
    priority: 4,
  },
  {
    id: 'preferences-9',
    category: 'preferences',
    question: 'Wie wichtig ist dir Nachhaltigkeit?',
    inputType: 'select',
    options: ['Sehr wichtig', 'Wichtig', 'Bemühe mich', 'Weniger wichtig', 'Nicht wichtig'],
    aiContextKey: 'nachhaltigkeit',
    priority: 6,
  },

  // ==================== HOBBIES (8 questions) ====================
  {
    id: 'hobbies-1',
    category: 'hobbies',
    question: 'Was machst du am liebsten in deiner Freizeit?',
    inputType: 'text',
    placeholder: 'z.B. Lesen, Gaming, Wandern...',
    aiContextKey: 'liebste_freizeitaktivitaet',
    priority: 2,
  },
  {
    id: 'hobbies-2',
    category: 'hobbies',
    question: 'Treibst du regelmäßig Sport?',
    inputType: 'select',
    options: ['Ja, täglich', 'Ja, mehrmals pro Woche', 'Ja, wöchentlich', 'Gelegentlich', 'Nein'],
    aiContextKey: 'sport_frequenz',
    priority: 4,
  },
  {
    id: 'hobbies-3',
    category: 'hobbies',
    question: 'Welche Sportart(en) magst du?',
    inputType: 'text',
    placeholder: 'z.B. Joggen, Fußball, Yoga...',
    aiContextKey: 'sportarten',
    priority: 5,
  },
  {
    id: 'hobbies-4',
    category: 'hobbies',
    question: 'Liest du gerne Bücher?',
    inputType: 'select',
    options: ['Ja, viel', 'Ja, manchmal', 'Nur Fachbücher', 'Eher Hörbücher', 'Nein'],
    aiContextKey: 'lesen_praeferenz',
    priority: 5,
  },
  {
    id: 'hobbies-5',
    category: 'hobbies',
    question: 'Welche Art von Filmen/Serien magst du?',
    inputType: 'text',
    placeholder: 'z.B. Action, Dokumentationen, Comedy...',
    aiContextKey: 'film_genre',
    priority: 7,
  },
  {
    id: 'hobbies-6',
    category: 'hobbies',
    question: 'Spielst du Videospiele?',
    inputType: 'select',
    options: ['Ja, regelmäßig', 'Ja, gelegentlich', 'Nur Mobile Games', 'Früher mal', 'Nein'],
    aiContextKey: 'gaming',
    priority: 7,
  },
  {
    id: 'hobbies-7',
    category: 'hobbies',
    question: 'Hast du ein kreatives Hobby?',
    inputType: 'text',
    placeholder: 'z.B. Malen, Musik, Fotografie...',
    aiContextKey: 'kreatives_hobby',
    priority: 5,
  },
  {
    id: 'hobbies-8',
    category: 'hobbies',
    question: 'Reist du gerne?',
    inputType: 'select',
    options: ['Ja, sehr oft', 'Ja, regelmäßig', 'Manchmal', 'Selten', 'Nein'],
    aiContextKey: 'reisen_praeferenz',
    priority: 6,
  },

  // ==================== COMMUNICATION (7 questions) ====================
  {
    id: 'communication-1',
    category: 'communication',
    question: 'Wie kommunizierst du am liebsten?',
    inputType: 'select',
    options: ['Persönlich', 'Videocall', 'Telefonat', 'Chat/Messenger', 'E-Mail'],
    aiContextKey: 'kommunikations_praeferenz',
    priority: 2,
  },
  {
    id: 'communication-2',
    category: 'communication',
    question: 'Verwendest du gerne Emojis in der Kommunikation?',
    inputType: 'select',
    options: ['Ja, viele', 'Ja, manchmal', 'Nur privat', 'Selten', 'Nein'],
    aiContextKey: 'emoji_nutzung',
    priority: 3,
  },
  {
    id: 'communication-3',
    category: 'communication',
    question: 'Wie schnell antwortest du auf Nachrichten?',
    inputType: 'select',
    options: ['Sofort', 'Innerhalb von Minuten', 'Innerhalb von Stunden', 'Am selben Tag', 'Wenn ich Zeit habe'],
    aiContextKey: 'antwortgeschwindigkeit',
    priority: 5,
  },
  {
    id: 'communication-4',
    category: 'communication',
    question: 'Bevorzugst du kurze oder ausführliche Nachrichten?',
    inputType: 'select',
    options: ['Sehr kurz', 'Kurz', 'Mittel', 'Ausführlich', 'Kommt drauf an'],
    aiContextKey: 'nachrichtenlaenge',
    priority: 3,
  },
  {
    id: 'communication-5',
    category: 'communication',
    question: 'Wie gehst du mit Konflikten um?',
    inputType: 'select',
    options: ['Direkt ansprechen', 'Diplomatisch', 'Vermeiden', 'Schriftlich klären', 'Mediator einbeziehen'],
    aiContextKey: 'konfliktbewaeltigung',
    priority: 4,
  },
  {
    id: 'communication-6',
    category: 'communication',
    question: 'Wie gibst du am liebsten Feedback?',
    inputType: 'select',
    options: ['Direkt und ehrlich', 'Konstruktiv verpackt', 'Schriftlich', 'Im 4-Augen-Gespräch', 'Ungern'],
    aiContextKey: 'feedback_stil',
    priority: 4,
  },
  {
    id: 'communication-7',
    category: 'communication',
    question: 'Wie wichtig ist dir Small Talk?',
    inputType: 'select',
    options: ['Sehr wichtig', 'Wichtig', 'Neutral', 'Weniger wichtig', 'Mag keinen Small Talk'],
    aiContextKey: 'small_talk',
    priority: 6,
  },

  // ==================== PRODUCTIVITY (7 questions) ====================
  {
    id: 'productivity-1',
    category: 'productivity',
    question: 'Wie planst du deinen Tag?',
    inputType: 'select',
    options: ['Detailliert mit Kalender', 'To-Do-Liste', 'Grob im Kopf', 'Spontan', 'Gar nicht'],
    aiContextKey: 'tagesplanung',
    priority: 2,
  },
  {
    id: 'productivity-2',
    category: 'productivity',
    question: 'Wann bist du am produktivsten?',
    inputType: 'select',
    options: ['Früh morgens', 'Vormittags', 'Mittags', 'Nachmittags', 'Abends', 'Nachts'],
    aiContextKey: 'produktivste_zeit',
    priority: 2,
  },
  {
    id: 'productivity-3',
    category: 'productivity',
    question: 'Welche Tools nutzt du für Produktivität?',
    inputType: 'text',
    placeholder: 'z.B. Notion, Todoist, Google Calendar...',
    aiContextKey: 'produktivitaets_tools',
    priority: 4,
  },
  {
    id: 'productivity-4',
    category: 'productivity',
    question: 'Wie gehst du mit Prokrastination um?',
    inputType: 'select',
    options: ['Pomodoro-Technik', 'Kleinere Aufgaben', 'Deadline-Druck', 'Belohnungen', 'Kämpfe damit'],
    aiContextKey: 'prokrastinations_strategie',
    priority: 4,
  },
  {
    id: 'productivity-5',
    category: 'productivity',
    question: 'Wie viele Tabs hast du typischerweise offen?',
    inputType: 'select',
    options: ['1-5', '6-10', '11-20', '21-50', 'Mehr als 50'],
    aiContextKey: 'browser_tabs',
    priority: 8,
  },
  {
    id: 'productivity-6',
    category: 'productivity',
    question: 'Nutzt du Tastaturkürzel?',
    inputType: 'select',
    options: ['Ja, sehr viele', 'Ja, einige', 'Die wichtigsten', 'Kaum', 'Nein'],
    aiContextKey: 'tastaturkuerzel',
    priority: 6,
  },
  {
    id: 'productivity-7',
    category: 'productivity',
    question: 'Wie hältst du deine Inbox unter Kontrolle?',
    inputType: 'select',
    options: ['Inbox Zero', 'Regelmäßig aufräumen', 'Filter/Regeln', 'Wichtiges zuerst', 'Gar nicht'],
    aiContextKey: 'inbox_management',
    priority: 5,
  },
] as const

/**
 * Get all questions
 */
export function getAllQuestions(): readonly DailyQuestion[] {
  return QUESTION_POOL
}

/**
 * Get question by ID
 */
export function getQuestionById(id: string): DailyQuestion | undefined {
  return QUESTION_POOL.find((q) => q.id === id)
}

/**
 * Get questions by category
 */
export function getQuestionsByCategory(
  category: DailyQuestion['category']
): readonly DailyQuestion[] {
  return QUESTION_POOL.filter((q) => q.category === category)
}

/**
 * Get unanswered questions
 */
export function getUnansweredQuestions(
  answeredIds: readonly string[]
): readonly DailyQuestion[] {
  return QUESTION_POOL.filter((q) => !answeredIds.includes(q.id))
}
