import type { OnboardingStep } from '@/types/profile'

export const ONBOARDING_STEPS: readonly OnboardingStep[] = [
  {
    id: 'job-role',
    type: 'hybrid',
    title: 'Was beschreibt deine Rolle am besten?',
    description: 'Hilft uns, den Ton deiner Nachrichten anzupassen.',
    options: [
      { value: 'developer', label: 'Entwickler/in' },
      { value: 'manager', label: 'Manager/in' },
      { value: 'designer', label: 'Designer/in' },
      { value: 'consultant', label: 'Berater/in' },
      { value: 'founder', label: 'Gründer/in' },
    ],
    textPlaceholder: 'Oder eigene Rolle eingeben...',
    profileField: 'jobRole',
  },
  {
    id: 'industry',
    type: 'hybrid',
    title: 'In welcher Branche arbeitest du?',
    description: 'Ermöglicht branchenspezifische Formulierungen.',
    options: [
      { value: 'tech', label: 'Technologie' },
      { value: 'finance', label: 'Finanzen' },
      { value: 'healthcare', label: 'Gesundheit' },
      { value: 'education', label: 'Bildung' },
      { value: 'creative', label: 'Kreativ/Medien' },
    ],
    textPlaceholder: 'Oder eigene Branche eingeben...',
    profileField: 'industry',
  },
  {
    id: 'company-size',
    type: 'select',
    title: 'Wie groß ist dein Unternehmen?',
    description: 'Beeinflusst den Kommunikationsstil.',
    options: [
      { value: 'solo', label: 'Solo/Freelancer' },
      { value: 'small', label: 'Klein (2-10)' },
      { value: 'medium', label: 'Mittel (11-50)' },
      { value: 'large', label: 'Groß (51-500)' },
      { value: 'enterprise', label: 'Konzern (500+)' },
    ],
    profileField: 'companySize',
  },
  {
    id: 'formality',
    type: 'select',
    title: 'Wie formal kommunizierst du normalerweise?',
    description: 'Bestimmt die Anrede und den Sprachstil.',
    options: [
      { value: 'casual', label: 'Locker', description: 'Du-Form, entspannt' },
      { value: 'neutral', label: 'Neutral', description: 'Situationsabhängig' },
      { value: 'formal', label: 'Formell', description: 'Sie-Form, professionell' },
      {
        value: 'very-formal',
        label: 'Sehr formell',
        description: 'Geschäftlich, konservativ',
      },
    ],
    profileField: 'formalityLevel',
  },
  {
    id: 'signature-name',
    type: 'text',
    title: 'Wie möchtest du E-Mails unterschreiben?',
    description: 'Wird am Ende deiner E-Mails verwendet.',
    textPlaceholder: 'z.B. Max, Max Budde, M. Budde',
    profileField: 'signatureName',
  },
  {
    id: 'use-case',
    type: 'select',
    title: 'Wofür wirst du VoiceOS hauptsächlich nutzen?',
    description: 'Optimiert die Ausgabeformate.',
    options: [
      { value: 'emails', label: 'E-Mails schreiben' },
      { value: 'meetings', label: 'Meeting-Notizen' },
      { value: 'tasks', label: 'Aufgaben & Todos' },
      { value: 'brainstorm', label: 'Brainstorming' },
      { value: 'general', label: 'Verschiedenes' },
    ],
    profileField: 'primaryUseCase',
  },
  {
    id: 'technical-level',
    type: 'select',
    title: 'Wie technisch ist dein Arbeitsumfeld?',
    description: 'Passt die Fachsprache an.',
    options: [
      { value: 'non-technical', label: 'Nicht technisch' },
      { value: 'some-technical', label: 'Etwas technisch' },
      { value: 'technical', label: 'Technisch' },
      { value: 'expert', label: 'Sehr technisch' },
    ],
    profileField: 'technicalLevel',
  },
  {
    id: 'output-length',
    type: 'select',
    title: 'Wie ausführlich sollen Texte standardmäßig sein?',
    description: 'Bestimmt die Standardlänge der Ausgaben.',
    options: [
      { value: 'concise', label: 'Kurz & knapp', description: 'Auf den Punkt' },
      { value: 'balanced', label: 'Ausgewogen', description: 'Goldene Mitte' },
      { value: 'detailed', label: 'Ausführlich', description: 'Mit Details' },
    ],
    profileField: 'preferredOutputLength',
  },
] as const
